### ISSUE TITLE
Using this with clientside blazor

### ISSUE THREAD

**Issue by americanslon** [dahomey-technologies/Dahomey.Json#32]
Do you know how this can be setup in the client side blazor to deserialized based on the descriminator.

The serialization on the net.core web api side works great, `_t` gets added but the blazor side is not aware of `_t` and doesn't deserialize into derived types.

**Comment by mcatanzariti** [comment]
@americanslon Are you referring to this technologie? 
https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor

**Comment by americanslon** [comment]
Yep that's the one.
Nothing fails, I don't even understand how to bootstrap/initialize it with blazor. 
Judging by your question you probably don't know either. It might be something worthwhile to look at to make sure this library works with it

**Comment by mcatanzariti** [comment]
Please let me help you by providing a code sample!

**Comment by americanslon** [comment]
There is nothing to provide....I don't understand how to set this up.
For example there are not controllers in blazor so there is no `JsonSerializerOptions` that I can find too attach Dahomey.Json to. Nothing to call `SetupExtensions` on.

**Comment by mcatanzariti** [comment]
What I am expecting is the code where you call GetJsonAsync or something similar to be sure I'm looking at the right API

Anyway, by digging into this technology, I noticed that there is no way to provide a JsonSerializerOptions instance to their HttpClient extension. 

You need to call Dahomey.Json extension method SetupExtension on JsonSerializerOptions in order to let polymorphism work.

the issue corresponding to this problem is here:
https://github.com/dotnet/aspnetcore/issues/19368

and the task to implement a better HttpClientExtensions is
https://github.com/dotnet/runtime/issues/32937

However, you could implement it yourself, starting from
https://github.com/dotnet/aspnetcore/blob/master/src/Components/Blazor/Http/src/HttpClientJsonExtensions.cs

for instance
```csharp
public static async Task<T> GetJsonAsync<T>(this HttpClient httpClient, string requestUri)
{
    var stringContent = await httpClient.GetStringAsync(requestUri);
    return JsonSerializer.Deserialize<T>(stringContent, JsonSerializerOptionsProvider.Options);
}
``` 
would be modified into
```csharp
public static async Task<T> GetJsonAsync<T>(this HttpClient httpClient, string requestUri, JsonSerializerOptions options)
{
    var stringContent = await httpClient.GetStringAsync(requestUri);
    return JsonSerializer.Deserialize<T>(stringContent, options);
}
``` 
Hope it helps
